---
- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: true

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link

- name: Clone git repo
  git:
    repo: "{{ item }}"
    dest: "/Users/{{ ansible_env.USER }}/Source/{{ item | basename }}"
    update: false
  with_items: "{{ git_repos }}"
